SELECT
MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH,'YYYY-MM-DD')
FROM MEMBER_PROFILE 
WHERE TLNO IS NOT NULL
AND SUBSTR(TO_CHAR(DATE_OF_BIRTH,'YYYYMMDD'),5,2) = '03'
AND GENDER = 'W'
ORDER BY MEMBER_ID