SELECT X.CATEGORY, SUM(X.SALES) AS TOTA_SALES
FROM (
SELECT A.CATEGORY,B.SALES
FROM BOOK A, BOOK_SALES B
WHERE A.BOOK_ID = B.BOOK_ID
AND TO_CHAR(B.SALES_DATE, 'YYYYMM') = '202201'
    ) X
GROUP BY X.CATEGORY
ORDER BY X.CATEGORY